server:
  port: 9965
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:5001/uaa/oauth/user/current
      id: user
      prefer-token-info: false
  sessions: stateless

spring:
  application:
    name: dummy-service
logging:
  level:
    org.springframework:
      security: DEBUG